apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: wishlist-cd-
spec:
  timeouts:
    pipeline: "3h0m0s"
  pipelineRef:
    name: wishlist-cd
  taskRunTemplate:
    serviceAccountName: wishlist-pipeline
  params:
    - name: repo-url
      value: https://github.com/CSCI-GA-2820-SU26-001/wishlists.git
    - name: revision
      value: master
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/kongzei-dev/wishlist:latest
    - name: base-url
      value: http://wishlist-kongzei-dev.apps.rm1.0a51.p1.openshiftapps.com
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
